default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || nil %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'blog_development' %>

test:
  <<: *default
  database: blog_test
  port: <%= (ENV['CI_NAME'] == 'codeship') ? 5433 : 5432 %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
